### ISSUE TITLE
Inconsistent message format. Additional and repetitive content shown.

### ISSUE THREAD

**Issue by drbgfc** [mdht/mdht#69]
The specific issue ahead is located in the consol2 model. It is suspected that it could be replicated in any model with a similar inline setup though. As, the content is generated.
For construction, See plugin.properties/
SocialHistoryObservation2SocialHistoryObservation2CDTranslation
and
SocialHistoryObservation2SocialHistoryObservation2CDTranslationP
and
SocialHistoryObservation2SocialHistoryObservationCode
and
SocialHistoryObservation2SocialHistoryObservationCodeP

For model location see consol2.uml/
SocialHistoryObservation2 template/code
and
SocialHistoryObservation2 template/CD inline class/translation

Actual Result:
Message: Consol Social History Observation (V3) SHALL contain exactly one [1..1] code with @xsi:type="CD" Consol CD SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)<b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslation <b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslationP     , which SHOULD be selected from ValueSet Social History Type 2.16.840.1.113883.3.88.12.80.60 STATIC 2008-12-18 (CONF:1198-8558) code SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)
Path: /ClinicalDocument/component/structuredBody/component[14]/section/entry[3]/observation/code
Line Number (approximate): 3145
Source: org.openhealthtools.mdht.uml.cda.consol 

Expected result:
Consol Social History Observation2 SHALL contain exactly one [1..1] code with @xsi:type="CD" Consol CD SHALL contain at least one [1..*] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)   , which SHOULD be selected from ValueSet Social History Type 2.16.840.1.113883.3.88.12.80.60 STATIC 2008-12-18 (CONF:1198-8558)

Specific issues which seem recent include:
1. The following codeSystem requirement is repeated at the end of the message for an unknown reason:
"which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)"
2. HTML is shown when it should not be there:
<b>SHALL</b>
3. Other extra content is shown such as property/method names:
satisfy: SocialHistoryObservation2CDTranslation ... satisfy: SocialHistoryObservation2CDTranslationP 
2/3: Basically, the entire line should not exist:
b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslation <b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslationP 

We should also address the way inline messages are presented, even in the expected result. The way the inline part is injected in the middle of the message could confuse some users. It should probably be written in a more linear fashion. This part of the issue is not a bug though, just preference.

**Comment by sarpkayanehta** [comment]
Hi,

How can I get the "Actual Result"? When I check SocialHistoryObservation2->code's conformance message in UML I get the message which is the same as expected result.

**Comment by drbgfc** [comment]
Thanks for looking.

You can either look here at the generated message:
/org.openhealthtools.mdht.uml.cda.consol2/plugin.properties
search for SocialHistoryObservation2SocialHistoryObservation2CDTranslation

Or

Run a validation of an XML document with the issue defined. I can provide one if you want. U can't attach XML here though.

**Comment by sarpkayanehta** [comment]
How can I generate the message? (Sorry it's a bit different than our models)

**Comment by drbgfc** [comment]
Np. Thanks again for looking.
Right click /org.openhealthtools.mdht.uml.cda.consol2/transform.xml -> run as -> ant build (make sure the JRE tab has 'Run in the same JRE as the workspace' selected if not selected already)
Just a heads up, it will take a good 3 - 5 mins to run.
I will look into the issue more in the morning as well.

**Comment by sarpkayanehta** [comment]
Okay so first thing that I know is running transformer.xml will always keep the markup enabled. I don't really know what would have started this issue, could you please give me some idea on the latest successful version that it didn't include the html markups?

Also I didn't know that we could get non DITA output. I can definitely look for the additional content issue if you can provide last successful version as well.

**Comment by drbgfc** [comment]
I started seeing markup (and the other issues) in this (latest) release:
https://github.com/mdht/mdht-models/releases/tag/Consol2_CCDAR2.1_Beta
2.5.4 models/gen (TS: 20150831), 2.5.9 plugins (TS: 20150901)
I don't recall the issues in any previous release. It's a bit difficult to check for this exact issue though since these exact inline (translation) modeling sequences did not exist then.It could be done though with some old jars and the new model. The last previous release was:
https://github.com/mdht/mdht-models/releases/tag/Consol2Gamma
2.5.2 models/gen, 2.5.4 plugins

Besides a conformance rule UI update feature and some added codeSystems, I haven't made any changes to the mdht plugin repo since the last release.

I will check the commits to get an idea of where to look for the changes.

**Comment by drbgfc** [comment]
I have determined that the problem is a global issue related to inline classes. Is not specific to any datatype, class, or attribute. There are over 2,901 instances of the bold HTML start tag which did not exist previously. They appear to always surround a severity and appear to always include the other 'satisfy' the method name bug as well, even though they aren't custom constraints. This information was gathered from searching the plugin.properties file.

**Comment by drbgfc** [comment]
Just a note: Commenting out the following code in /org.openhealthtools.mdht.uml.cda.core/src/org/openhealthtools/mdht/uml/cda/core/util/CDAModelUtil.java removes both markup instances and the 'satisfy' part of the bug in 99.9% of instances. The property name and repeated line issue still exist:

~ line 1621

``` java
        if (displayBody == null || !containsSeverityWord(displayBody)) {
            String keyword = getValidationKeyword(constraint);
            if (keyword == null) {
                keyword = "SHALL";
            }

            message.append(markup
                    ? "<b>"
                    : "");
            message.append(keyword);
            message.append(markup
                    ? "</b>"
                    : "");
            message.append(" satisfy: ");
        }
```

specific example With source code above
SocialHistoryObservation2SocialHistoryObservation2CDTranslation = 
Consol Social History Observation (V3) SHALL contain exactly one [1..1] code with @xsi:type="CD" Consol CD SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)<b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslation <b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslationP     , which SHOULD be selected from ValueSet Social History Type 2.16.840.1.113883.3.88.12.80.60 STATIC 2008-12-18 (CONF:1198-8558) code SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)

specific example Without source code above
SocialHistoryObservation2SocialHistoryObservation2CDTranslation = 
Consol Social History Observation (V3) SHALL contain exactly one [1..1] code with @xsi:type="CD" Consol CD SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)SocialHistoryObservation2CDTranslation SocialHistoryObservation2CDTranslationP     , which SHOULD be selected from ValueSet Social History Type 2.16.840.1.113883.3.88.12.80.60 STATIC 2008-12-18 (CONF:1198-8558) code SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)

**Comment by drbgfc** [comment]
Commenting out the following source code line removes the excess property names in the message. The issue is related to the way this source and the above source handles display body Being null. This allows the code to run which in my scenario is not required. So, I suspect, either we need an extra condition for my case to work as it did before, or, we don't need the code to begin with.
~ line 1619

commented out line 1619 from the following block:

``` java
message.append(constraint.getName());
```

``` java
        if (displayBody == null) {
            message.append(constraint.getName());
        } else {
            message.append(displayBody);
        }
```

specific example Without source code above (or 1621 related source)
SocialHistoryObservation2SocialHistoryObservation2CDTranslation = 
Consol Social History Observation (V3) SHALL contain exactly one [1..1] code with @xsi:type="CD" Consol CD SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)      , which SHOULD be selected from ValueSet Social History Type 2.16.840.1.113883.3.88.12.80.60 STATIC 2008-12-18 (CONF:1198-8558) code SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)

The property names in the message were removed to further match the expected example. It's interesting to note that both the terminology and property names are listed.
Removed text:
SocialHistoryObservation2CDTranslation SocialHistoryObservation2CDTranslationP

The only issue that remains (besides revising the code to work for both of our scenarios) is the repeated line for (CONF:1198-32853)
This may or may not be related to recent message generation changes.

**Comment by sarpkayanehta** [comment]
Hi,

Sorry for the late response. I did tests from 2.5.9 till 2.5.4 and I am still getting the markup issue. I don't think that's a recent issue. From what I know in MDHT when transformer is run, markup is activated, and if you use conformance message box within MDHT, then markup is disabled.
In my 2.5.4 I am getting the below message:

Consol Social History Observation (V3) SHALL contain exactly one [1..1] code with @xsi:type="CD" Consol CD SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)<b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslation <b>SHALL</b> satisfy: SocialHistoryObservation2CDTranslationP     , which SHOULD be selected from ValueSet Social History Type 2.16.840.1.113883.3.88.12.80.60 STATIC 2008-12-18 (CONF:1198-8558) code SHALL contain at least one [1.._] translation, which SHOULD be selected from (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-32853)

Which looks the same as the one you posted above.

Unfortunately I cannot get below 2.5.4 version I think model relies on some changes that were made since 2.5.4

**Comment by sarpkayanehta** [comment]
For the ~ line 1621 in CDAModelUtil, that code is pretty old I can go back to git history and can still find that the code was there 4 years ago with the markup. Sorry I am not too sure how you were able to get without any markup before. Perhaps your way of building somehow disabled markup settings?

Again looking at the other code, that's also pretty old (still exists for longer than 4 years).

Having said that, if you think that is not necessary for generated documents, then we can check if markup is there as a pre condition (although you will still get markups).

**Comment by drbgfc** [comment]
The markup issue with the bold tag was a bug introduced by a hard coded true at some point before this latest build. The markup variable will replace true.
See 1251

``` java
assocConstraints = CDAModelUtil.computeAssociationConstraints(property, true);
```

and 1259

``` java
ruleConstraints.append(li[0] + CDAModelUtil.computeConformanceMessage(constraint, true));
```

There are two other instances as well.

The property, SHALL, satisfy, and repetition issues still need to be resolved. The plan is to rewrite them so they work as they did previously, using the newly introduced helper methods which have modified the logic. We will need to ensure there is no issue for plugin.properties (SITE work) and DITA output (NEHTA work) once complete.

**Comment by drbgfc** [comment]
There is a pull request here to fix the issues.
https://github.com/mdht/mdht/pull/80
The specific changes cannot be seen due to the code cleanup used prior to this commit not being the same as previous commits.
Basically in some cases properties were being treated as custom constraints and being updated w/o any stereotypes applied. In another instance computeConformanceMessage was being called redundantly. Still unsure how <i>exactly</i> this changed ~3 months ago and worked for the last 3+ years otherwise. But no matter, it is fixed.

**Comment by drbgfc** [comment]
To get our source cleanup to match the format of all existing code:
Create a profile with the following details (start with default add the 2 or 3 changes) and run source cleanup before a commit. There may still be issues between Mac/Windows/Linux however:

Change non static accesses to static members using declaring type
Change indirect accesses to static members to direct accesses (accesses through subtypes)
Convert control statement bodies to block
Remove unused imports
Remove unused local variables
Add missing '@Override' annotations
Add missing '@Deprecated' annotations
Remove unnecessary casts
Remove unnecessary '$NON-NLS$' tags
Format source code
Remove trailing white spaces on all lines

**Comment by drbgfc** [comment]
The pull request has been merged and the issue has been tested.
Closing.
