### ISSUE TITLE
recent bugs introduced by business-name-update pull request #73

### ISSUE THREAD

**Issue by drbgfc** [mdht/mdht#89]
<b>Issue 1 (critical):</b>
A very recent (within one week) change to the plugins has significantly altered the plugin.properties output to the point where all constraints within the template (with a business name) are now unusable for validation reporting as nothing can be referenced properly.
It also changes what's represented in Ecore (see Advance Directive Organizer (V2) in example image):
![image](https://cloud.githubusercontent.com/assets/5495334/10259867/991aba4c-693b-11e5-92b3-22b9778d130f.png)
It also causes compile errors in the generated code (559 for R2.1 mostly related to fields not resolving).

See how the keys have changed from usable constants to a 2x duplicated business name followed by the final property. This happens when a new business name is saved in a root template and a transform is run. Don't worry about the differences in the values themselves as these were updated in https://github.com/mdht/mdht/commit/b1119ca334a86c299d2cd4c24bba68c8d3b84bae. Just look at the keys.

example:
<strong>old format:</strong>
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerAdvanceDirectiveObservation2 = Consol Advance Directive Organizer SHALL contain  [1.._] component (CONF:1098-28420, CONF:1098-28421) Contains exactly one [1..1] Advance Directive Observation (V3) (templateId: 2.16.840.1.113883.10.20.22.4.48:2015-08-01)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerAuthorParticipation = Consol Advance Directive Organizer SHOULD contain  [0.._] author (CONF:1098-32407) Contains exactly one [1..1] Author Participation (templateId: 2.16.840.1.113883.10.20.22.4.119)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerClassCode = Consol Advance Directive Organizer SHALL contain exactly one [1..1] @classCode="CLUSTER"  (CodeSystem: 2.16.840.1.113883.5.6 HL7ActClass) (CONF:1098-28410)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerCode = Consol Advance Directive Organizer SHALL contain exactly one [1..1] code (CONF:1098-28415)/@code="45473-6" Advance directive - living will (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1098-31230, CONF:1098-31231)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerCodeP = Consol Advance Directive Organizer SHALL contain exactly one [1..1] code (CONF:1098-28415)/@code="45473-6" Advance directive - living will (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1098-31230, CONF:1098-31231)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerId = Consol Advance Directive Organizer SHALL contain at least one [1..*] id (CONF:1098-28414)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerMoodCode = Consol Advance Directive Organizer SHALL contain exactly one [1..1] @moodCode="EVN" Event (CodeSystem: 2.16.840.1.113883.5.1001 HL7ActMood) (CONF:1098-28411)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerStatusCode = Consol Advance Directive Organizer SHALL contain exactly one [1..1] statusCode (CONF:1098-28418)/@code="completed"  (CodeSystem: 2.16.840.1.113883.5.14 ActStatus) (CONF:1098-31346)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerStatusCodeP = Consol Advance Directive Organizer SHALL contain exactly one [1..1] statusCode (CONF:1098-28418)/@code="completed"  (CodeSystem: 2.16.840.1.113883.5.14 ActStatus) (CONF:1098-31346)
AdvanceDirectiveOrganizerAdvanceDirectiveOrganizerTemplateId = SHALL contain exactly one [1..1] templateId ( CONF:1098-28412, CONF:1098-28413 ) such that it SHALL contain exactly one [1..1] @root="2.16.840.1.113883.10.20.22.4.108" and SHALL contain exactly one [1..1] @extension="2015-08-01"

<strong>new format:</strong>
Advance Directive Organizer (V2)Advance Directive Organizer (V2)AdvanceDirectiveObservation2 = Advance Directive Organizer (V2) (V2) SHALL contain  [1.._] component (CONF:1198-28420, CONF:1198-28421) Contains exactly one [1..1] Advance Directive Observation (V3) (templateId: 2.16.840.1.113883.10.20.22.4.48:2015-08-01)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)AuthorParticipation = Advance Directive Organizer (V2) (V2) SHOULD contain  [0.._] author (CONF:1198-32407) Contains exactly one [1..1] Author Participation (templateId: 2.16.840.1.113883.10.20.22.4.119)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)ClassCode = Advance Directive Organizer (V2) (V2) SHALL contain exactly one [1..1] @classCode="CLUSTER"  (CodeSystem: 2.16.840.1.113883.5.6 HL7ActClass) (CONF:1198-28410)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)Code = Advance Directive Organizer (V2) (V2) SHALL contain exactly one [1..1] code (CONF:1198-28415)/@code="45473-6" Advance directive - living will (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-31230, CONF:1198-31231)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)CodeP = Advance Directive Organizer (V2) (V2) SHALL contain exactly one [1..1] code (CONF:1198-28415)/@code="45473-6" Advance directive - living will (CodeSystem: 2.16.840.1.113883.6.1 LOINC) (CONF:1198-31230, CONF:1198-31231)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)Id = Advance Directive Organizer (V2) (V2) SHALL contain at least one [1..*] id (CONF:1198-28414)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)MoodCode = Advance Directive Organizer (V2) (V2) SHALL contain exactly one [1..1] @moodCode="EVN" Event (CodeSystem: 2.16.840.1.113883.5.1001 HL7ActMood) (CONF:1198-28411)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)StatusCode = Advance Directive Organizer (V2) (V2) SHALL contain exactly one [1..1] statusCode (CONF:1198-28418)/@code="completed"  (CodeSystem: 2.16.840.1.113883.5.14 ActStatus) (CONF:1198-31346)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)StatusCodeP = Advance Directive Organizer (V2) (V2) SHALL contain exactly one [1..1] statusCode (CONF:1198-28418)/@code="completed"  (CodeSystem: 2.16.840.1.113883.5.14 ActStatus) (CONF:1198-31346)
Advance Directive Organizer (V2)Advance Directive Organizer (V2)TemplateId = SHALL contain exactly one [1..1] templateId ( CONF:1198-28412, CONF:1198-28413, CONF:1198-32876 ) such that it SHALL contain exactly one [1..1] @root="2.16.840.1.113883.10.20.22.4.108" and SHALL contain exactly one [1..1] @extension="2015-08-01"

<b>issue 2:</b>
Existing models (which have templates with business names saved) are not affected by the update. Only new modifications save the new format.
It works when I change a current business name but does not show existing ones. I assume because they are not stored in the properties in the manner required/added.

I am hoping we can resolve these issues soon. #1 more importantly. I don't think it will be complicated. We just need to separate the logic for business names from normal names (as it was before).
For #2, I would look into using the existing labels which were already saved for business names instead of using a new one. For example, _label_ instead of _name_. Any model which already had a business name already has a property saved with a _label_... key and an associated business name value. Maybe that system doesn't make sense either though.
For me, personally, once fixed, I will need to know how to manually fix what has been altered as I have a lot of pending model project work to commit, which was running the latest code with this bug.

If not seeing the issues I could commit my current branch for review. Just let me know. I should have all the latest code except for Dave's eclipse PRs and Vadim's version PR. My process was, 
after this was merged a few days ago https://github.com/mdht/mdht/commit/b1119ca334a86c299d2cd4c24bba68c8d3b84bae to merge all of the latest mdht dev code into my fork here: https://github.com/drbgfc/mdht in workingBranch.
see comparison here:
https://github.com/drbgfc/mdht/compare/workingBranch...mdht:develop

**Comment by drbgfc** [comment]
My model branch is pushed now with the bug.
https://github.com/mdht/mdht-models/tree/1drb_R2.1_FinishEntries

This may help to see how the controlled model properties are being updated:
https://github.com/mdht/mdht-models/commit/732022526f735ca8421e38ac651b9033712360d7

**Comment by drbgfc** [comment]
Here is a link to what the properties looked like (in full) before this bug:
https://raw.githubusercontent.com/mdht/mdht-models/develop/generated/org.openhealthtools.mdht.uml.cda.consol2/plugin.properties

i have not committed the broken version of the plugin.properties or anything to the gen project.

**Comment by drbgfc** [comment]
If you save the following file as a text file you can view it. Github wouldn't accept a text file that large (or a properties file type at all). It's the full newly generated plugin.properties.
![pluginproperties](https://cloud.githubusercontent.com/assets/5495334/10260403/33a5274e-6943-11e5-9b26-14c8276aa005.png)

**Comment by drbgfc** [comment]
PR the issue is be related to: 
<a href="https://github.com/mdht/mdht/commit/b5fee09e361c668167724848e01cc5d354d672d3">PR 73</a>

**Comment by drbgfc** [comment]
The issue is from an update to NamedElementSection.java in the above pull 73.
/org.openhealthtools.mdht.uml.ui.properties/src/org/openhealthtools/mdht/uml/ui/properties/internal/sections/NamedElementSection.java

I reverted the above file only and, along with reverting some test properties and re-saving them using the reverted NamedElementSection.java, all issues are resolved,

This will need to be rewritten.

**Comment by sarpkayanehta** [comment]
I see why this is happening. I was thinking of not using localNameText for displaying anything but it appears to be the case.

I guess simplest fix I can do is to retrieve localNameText value back.

**Comment by drbgfc** [comment]
Cool. For now since you are ok with it we will revert. I can test the next PR a little before it is merged. Or, if you have a personal plugin branch I can test that before the next PR is submitted.

**Comment by drbgfc** [comment]
I think you should probably just use the existing saved business names that are in the properties under the 'label' format. Nothing is really being done with them other than them being saved currently. This way, when implemented, current models will work as is. I am not exactly sure why the new 'name' format is needed for business names? But, whatever works is fine.
